<?php

namespace Database\Seeders;

use App\Models\Building;
use App\Models\Floor;
use App\Models\Inventory;
use App\Models\InventoryTransaction;
use App\Models\Lamp;
use App\Models\LampType;
use App\Models\Maintenance;
use App\Models\Transaction;
use Carbon\Carbon;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Schema;

class FmLightningSeeder extends Seeder
{
    private $lampCounter = 1;

    public function run(): void
    {
        // Disable foreign key constraints and truncate existing tables for clean seed IDs
        Schema::disableForeignKeyConstraints();
        Building::truncate();
        Floor::truncate();
        LampType::truncate();
        Lamp::truncate();
        Inventory::truncate();
        InventoryTransaction::truncate();
        Transaction::truncate();
        Maintenance::truncate();
        Schema::enableForeignKeyConstraints();

        // 1. Create Building
        $building = Building::create([
            'name' => 'Gedung A',
            'location' => 'Jakarta Utama',
            'description' => 'Gedung Operasional & Kantor Pusat SIDERAL',
        ]);

        $buildingB = Building::create([
            'name' => 'Gedung B',
            'location' => 'Jakarta Barat',
            'description' => 'Gedung Cabang B',
        ]);

        // 2. Create Floors
        $floors = [
            'L1' => Floor::create(['building_id' => $building->id, 'name' => 'Lantai 1', 'floor_number' => 1]),
            'L2' => Floor::create(['building_id' => $building->id, 'name' => 'Lantai 2', 'floor_number' => 2]),
            'L3' => Floor::create(['building_id' => $building->id, 'name' => 'Lantai 3', 'floor_number' => 3]),
            'LPH' => Floor::create(['building_id' => $building->id, 'name' => 'Lantai PH B', 'floor_number' => 4]),
            'L1B' => Floor::create(['building_id' => $buildingB->id, 'name' => 'Lantai 1', 'floor_number' => 1]),
            'L2B' => Floor::create(['building_id' => $buildingB->id, 'name' => 'Lantai 2', 'floor_number' => 2]),
        ];

        // 3. Create Lamp Types (matching the plan legend exactly)
        $lampTypes = [
            'halogen' => LampType::create([
                'name' => 'Lampu Halogen LED 5 Watt',
                'type' => 'Halogen',
                'shape' => 'segitiga',
                'watt' => 5,
                'price' => 25000,
                'status' => 'aktif'
            ]),
            'downlight' => LampType::create([
                'name' => 'Lampu Down Light Bulb 12 Watt',
                'type' => 'Downlight',
                'shape' => 'bulat',
                'watt' => 12,
                'price' => 35000,
                'status' => 'aktif'
            ]),
            't5' => LampType::create([
                'name' => 'Lampu T5 16 Watt LED x 1 Pcs',
                'type' => 'T5',
                'shape' => 'garis',
                'watt' => 16,
                'price' => 50000,
                'status' => 'aktif'
            ]),
            'tl_1' => LampType::create([
                'name' => 'Lampu TL 16 Watt LED x 1 Pcs',
                'type' => 'TL 1',
                'shape' => 'garis',
                'watt' => 16,
                'price' => 60000,
                'status' => 'aktif'
            ]),
            'tl_2' => LampType::create([
                'name' => 'Lampu TL 16 Watt LED x 2 Pcs',
                'type' => 'TL 2',
                'shape' => 'persegi_panjang',
                'watt' => 16,
                'price' => 75000,
                'status' => 'aktif'
            ]),
        ];

        // 4. seed lamp
        $typeMapping = [
            9 => $lampTypes['tl_2']->id,
            6 => $lampTypes['tl_2']->id,
            8 => $lampTypes['tl_2']->id,
            10 => $lampTypes['t5']->id,
        ];

        $rawLamps = [
            [
                'floor_id' => 5,
                'lamp_type_id' => 9,
                'code' => 'L-0001',
                'position_x' => 87,
                'position_y' => 17,
                'rotation' => 0,
                'width' => 32,
                'height' => 14,
                'status' => 'on',
                'installed_date' => null,
                'created_at' => '2026-07-23 00:15:31',
                'updated_at' => '2026-07-23 00:15:31',
            ],
            [
                'floor_id' => 5,
                'lamp_type_id' => 6,
                'code' => 'L-0338',
                'position_x' => 84,
                'position_y' => 20,
                'rotation' => 0,
                'width' => 32,
                'height' => 14,
                'status' => 'on',
                'installed_date' => null,
                'created_at' => '2026-07-23 00:15:45',
                'updated_at' => '2026-07-23 00:16:33',
            ],
            [
                'floor_id' => 5,
                'lamp_type_id' => 6,
                'code' => 'L-0339',
                'position_x' => 91,
                'position_y' => 19,
                'rotation' => 0,
                'width' => 32,
                'height' => 14,
                'status' => 'on',
                'installed_date' => null,
                'created_at' => '2026-07-23 00:16:30',
                'updated_at' => '2026-07-23 00:16:30',
            ],
            [
                'floor_id' => 5,
                'lamp_type_id' => 6,
                'code' => 'L-0340',
                'position_x' => 84,
                'position_y' => 40,
                'rotation' => 0,
                'width' => 32,
                'height' => 14,
                'status' => 'on',
                'installed_date' => null,
                'created_at' => '2026-07-23 00:16:45',
                'updated_at' => '2026-07-23 00:16:59',
            ],
            [
                'floor_id' => 5,
                'lamp_type_id' => 6,
                'code' => 'L-0341',
                'position_x' => 91,
                'position_y' => 40,
                'rotation' => 0,
                'width' => 32,
                'height' => 14,
                'status' => 'on',
                'installed_date' => null,
                'created_at' => '2026-07-23 00:16:56',
                'updated_at' => '2026-07-23 00:16:56',
            ],
            [
                'floor_id' => 5,
                'lamp_type_id' => 8,
                'code' => 'L-0342',
                'position_x' => 87,
                'position_y' => 53,
                'rotation' => 0,
                'width' => 32,
                'height' => 14,
                'status' => 'on',
                'installed_date' => null,
                'created_at' => '2026-07-23 00:18:01',
                'updated_at' => '2026-07-23 02:20:41',
            ],
            [
                'floor_id' => 5,
                'lamp_type_id' => 8,
                'code' => 'L-0343',
                'position_x' => 87,
                'position_y' => 55,
                'rotation' => 0,
                'width' => 32,
                'height' => 14,
                'status' => 'on',
                'installed_date' => null,
                'created_at' => '2026-07-23 00:18:12',
                'updated_at' => '2026-07-23 00:18:20',
            ],
            [
                'floor_id' => 5,
                'lamp_type_id' => 8,
                'code' => 'L-0344',
                'position_x' => 87,
                'position_y' => 61,
                'rotation' => 0,
                'width' => 32,
                'height' => 14,
                'status' => 'on',
                'installed_date' => null,
                'created_at' => '2026-07-23 00:18:37',
                'updated_at' => '2026-07-23 00:18:50',
            ],
            [
                'floor_id' => 5,
                'lamp_type_id' => 8,
                'code' => 'L-0345',
                'position_x' => 87,
                'position_y' => 63,
                'rotation' => 0,
                'width' => 32,
                'height' => 14,
                'status' => 'on',
                'installed_date' => null,
                'created_at' => '2026-07-23 00:18:54',
                'updated_at' => '2026-07-23 00:19:02',
            ],
            [
                'floor_id' => 5,
                'lamp_type_id' => 8,
                'code' => 'L-0346',
                'position_x' => 14,
                'position_y' => 21,
                'rotation' => 0,
                'width' => 32,
                'height' => 14,
                'status' => 'on',
                'installed_date' => null,
                'created_at' => '2026-07-23 00:19:32',
                'updated_at' => '2026-07-23 00:29:28',
            ],
            [
                'floor_id' => 5,
                'lamp_type_id' => 8,
                'code' => 'L-0347',
                'position_x' => 14,
                'position_y' => 23,
                'rotation' => 0,
                'width' => 32,
                'height' => 14,
                'status' => 'on',
                'installed_date' => null,
                'created_at' => '2026-07-23 00:19:40',
                'updated_at' => '2026-07-23 01:18:37',
            ],
            [
                'floor_id' => 5,
                'lamp_type_id' => 8,
                'code' => 'L-0348',
                'position_x' => 14,
                'position_y' => 33,
                'rotation' => 0,
                'width' => 32,
                'height' => 14,
                'status' => 'on',
                'installed_date' => null,
                'created_at' => '2026-07-23 00:21:41',
                'updated_at' => '2026-07-23 00:51:17',
            ],
            [
                'floor_id' => 5,
                'lamp_type_id' => 8,
                'code' => 'L-0349',
                'position_x' => 14,
                'position_y' => 35,
                'rotation' => 0,
                'width' => 32,
                'height' => 14,
                'status' => 'on',
                'installed_date' => null,
                'created_at' => '2026-07-23 00:21:47',
                'updated_at' => '2026-07-23 01:17:59',
            ],
            [
                'floor_id' => 5,
                'lamp_type_id' => 8,
                'code' => 'L-0350',
                'position_x' => 14,
                'position_y' => 45,
                'rotation' => 0,
                'width' => 32,
                'height' => 14,
                'status' => 'on',
                'installed_date' => null,
                'created_at' => '2026-07-23 00:22:15',
                'updated_at' => '2026-07-23 00:52:07',
            ],
            [
                'floor_id' => 5,
                'lamp_type_id' => 8,
                'code' => 'L-0351',
                'position_x' => 14,
                'position_y' => 47,
                'rotation' => 0,
                'width' => 32,
                'height' => 14,
                'status' => 'on',
                'installed_date' => null,
                'created_at' => '2026-07-23 00:22:26',
                'updated_at' => '2026-07-23 01:17:39',
            ],
            [
                'floor_id' => 5,
                'lamp_type_id' => 8,
                'code' => 'L-0352',
                'position_x' => 14,
                'position_y' => 58,
                'rotation' => 0,
                'width' => 32,
                'height' => 14,
                'status' => 'on',
                'installed_date' => null,
                'created_at' => '2026-07-23 00:22:53',
                'updated_at' => '2026-07-23 00:53:00',
            ],
            [
                'floor_id' => 5,
                'lamp_type_id' => 8,
                'code' => 'L-0353',
                'position_x' => 14,
                'position_y' => 60,
                'rotation' => 0,
                'width' => 32,
                'height' => 14,
                'status' => 'on',
                'installed_date' => null,
                'created_at' => '2026-07-23 00:23:01',
                'updated_at' => '2026-07-23 01:17:24',
            ],
            [
                'floor_id' => 5,
                'lamp_type_id' => 8,
                'code' => 'L-0354',
                'position_x' => 25,
                'position_y' => 21,
                'rotation' => 0,
                'width' => 32,
                'height' => 14,
                'status' => 'on',
                'installed_date' => null,
                'created_at' => '2026-07-23 00:32:13',
                'updated_at' => '2026-07-23 00:53:49',
            ],
            [
                'floor_id' => 5,
                'lamp_type_id' => 8,
                'code' => 'L-0355',
                'position_x' => 25,
                'position_y' => 23,
                'rotation' => 0,
                'width' => 32,
                'height' => 14,
                'status' => 'on',
                'installed_date' => null,
                'created_at' => '2026-07-23 00:32:57',
                'updated_at' => '2026-07-23 01:18:42',
            ],
            [
                'floor_id' => 5,
                'lamp_type_id' => 8,
                'code' => 'L-0356',
                'position_x' => 25,
                'position_y' => 33,
                'rotation' => 0,
                'width' => 32,
                'height' => 14,
                'status' => 'on',
                'installed_date' => null,
                'created_at' => '2026-07-23 00:33:33',
                'updated_at' => '2026-07-23 00:54:43',
            ],
            [
                'floor_id' => 5,
                'lamp_type_id' => 8,
                'code' => 'L-0357',
                'position_x' => 25,
                'position_y' => 35,
                'rotation' => 0,
                'width' => 32,
                'height' => 14,
                'status' => 'on',
                'installed_date' => null,
                'created_at' => '2026-07-23 00:33:50',
                'updated_at' => '2026-07-23 01:18:07',
            ],
            [
                'floor_id' => 5,
                'lamp_type_id' => 8,
                'code' => 'L-0358',
                'position_x' => 25,
                'position_y' => 45,
                'rotation' => 0,
                'width' => 32,
                'height' => 14,
                'status' => 'on',
                'installed_date' => null,
                'created_at' => '2026-07-23 00:34:02',
                'updated_at' => '2026-07-23 01:17:32',
            ],
            [
                'floor_id' => 5,
                'lamp_type_id' => 8,
                'code' => 'L-0359',
                'position_x' => 25,
                'position_y' => 47,
                'rotation' => 0,
                'width' => 32,
                'height' => 14,
                'status' => 'on',
                'installed_date' => null,
                'created_at' => '2026-07-23 00:44:29',
                'updated_at' => '2026-07-23 01:17:35',
            ],
            [
                'floor_id' => 5,
                'lamp_type_id' => 8,
                'code' => 'L-0360',
                'position_x' => 25,
                'position_y' => 58,
                'rotation' => 0,
                'width' => 32,
                'height' => 14,
                'status' => 'on',
                'installed_date' => null,
                'created_at' => '2026-07-23 00:45:21',
                'updated_at' => '2026-07-23 00:55:51',
            ],
            [
                'floor_id' => 5,
                'lamp_type_id' => 8,
                'code' => 'L-0361',
                'position_x' => 25,
                'position_y' => 60,
                'rotation' => 0,
                'width' => 32,
                'height' => 14,
                'status' => 'on',
                'installed_date' => null,
                'created_at' => '2026-07-23 00:45:47',
                'updated_at' => '2026-07-23 01:17:20',
            ],
            [
                'floor_id' => 5,
                'lamp_type_id' => 8,
                'code' => 'L-0362',
                'position_x' => 36,
                'position_y' => 21,
                'rotation' => 0,
                'width' => 32,
                'height' => 14,
                'status' => 'on',
                'installed_date' => null,
                'created_at' => '2026-07-23 00:46:09',
                'updated_at' => '2026-07-23 00:56:09',
            ],
            [
                'floor_id' => 5,
                'lamp_type_id' => 8,
                'code' => 'L-0363',
                'position_x' => 36,
                'position_y' => 23,
                'rotation' => 0,
                'width' => 32,
                'height' => 14,
                'status' => 'on',
                'installed_date' => null,
                'created_at' => '2026-07-23 00:46:41',
                'updated_at' => '2026-07-23 01:18:54',
            ],
            [
                'floor_id' => 5,
                'lamp_type_id' => 8,
                'code' => 'L-0364',
                'position_x' => 36,
                'position_y' => 33,
                'rotation' => 0,
                'width' => 32,
                'height' => 14,
                'status' => 'on',
                'installed_date' => null,
                'created_at' => '2026-07-23 00:46:57',
                'updated_at' => '2026-07-23 01:18:15',
            ],
            [
                'floor_id' => 5,
                'lamp_type_id' => 8,
                'code' => 'L-0365',
                'position_x' => 36,
                'position_y' => 35,
                'rotation' => 0,
                'width' => 32,
                'height' => 14,
                'status' => 'on',
                'installed_date' => null,
                'created_at' => '2026-07-23 00:47:33',
                'updated_at' => '2026-07-23 01:18:20',
            ],
            [
                'floor_id' => 5,
                'lamp_type_id' => 8,
                'code' => 'L-0366',
                'position_x' => 36,
                'position_y' => 45,
                'rotation' => 0,
                'width' => 32,
                'height' => 14,
                'status' => 'on',
                'installed_date' => null,
                'created_at' => '2026-07-23 00:56:19',
                'updated_at' => '2026-07-23 00:57:50',
            ],
            [
                'floor_id' => 5,
                'lamp_type_id' => 8,
                'code' => 'L-0367',
                'position_x' => 36,
                'position_y' => 47,
                'rotation' => 0,
                'width' => 32,
                'height' => 14,
                'status' => 'on',
                'installed_date' => null,
                'created_at' => '2026-07-23 00:56:24',
                'updated_at' => '2026-07-23 01:17:44',
            ],
            [
                'floor_id' => 5,
                'lamp_type_id' => 8,
                'code' => 'L-0368',
                'position_x' => 36,
                'position_y' => 58,
                'rotation' => 0,
                'width' => 32,
                'height' => 14,
                'status' => 'on',
                'installed_date' => null,
                'created_at' => '2026-07-23 00:56:31',
                'updated_at' => '2026-07-23 01:16:53',
            ],
            [
                'floor_id' => 5,
                'lamp_type_id' => 8,
                'code' => 'L-0369',
                'position_x' => 36,
                'position_y' => 60,
                'rotation' => 0,
                'width' => 32,
                'height' => 14,
                'status' => 'on',
                'installed_date' => null,
                'created_at' => '2026-07-23 00:56:36',
                'updated_at' => '2026-07-23 01:16:59',
            ],
            [
                'floor_id' => 5,
                'lamp_type_id' => 8,
                'code' => 'L-0370',
                'position_x' => 46,
                'position_y' => 20,
                'rotation' => 0,
                'width' => 32,
                'height' => 14,
                'status' => 'on',
                'installed_date' => null,
                'created_at' => '2026-07-23 00:56:42',
                'updated_at' => '2026-07-23 00:59:54',
            ],
            [
                'floor_id' => 5,
                'lamp_type_id' => 8,
                'code' => 'L-0371',
                'position_x' => 46,
                'position_y' => 22,
                'rotation' => 0,
                'width' => 32,
                'height' => 14,
                'status' => 'on',
                'installed_date' => null,
                'created_at' => '2026-07-23 00:58:08',
                'updated_at' => '2026-07-23 01:00:03',
            ],
            [
                'floor_id' => 5,
                'lamp_type_id' => 8,
                'code' => 'L-0372',
                'position_x' => 46,
                'position_y' => 33,
                'rotation' => 0,
                'width' => 32,
                'height' => 14,
                'status' => 'on',
                'installed_date' => null,
                'created_at' => '2026-07-23 00:58:14',
                'updated_at' => '2026-07-23 01:18:27',
            ],
            [
                'floor_id' => 5,
                'lamp_type_id' => 8,
                'code' => 'L-0373',
                'position_x' => 46,
                'position_y' => 35,
                'rotation' => 0,
                'width' => 32,
                'height' => 14,
                'status' => 'on',
                'installed_date' => null,
                'created_at' => '2026-07-23 00:58:19',
                'updated_at' => '2026-07-23 01:18:29',
            ],
            [
                'floor_id' => 5,
                'lamp_type_id' => 8,
                'code' => 'L-0374',
                'position_x' => 46,
                'position_y' => 45,
                'rotation' => 0,
                'width' => 32,
                'height' => 14,
                'status' => 'on',
                'installed_date' => null,
                'created_at' => '2026-07-23 00:58:24',
                'updated_at' => '2026-07-23 01:01:22',
            ],
            [
                'floor_id' => 5,
                'lamp_type_id' => 8,
                'code' => 'L-0375',
                'position_x' => 46,
                'position_y' => 47,
                'rotation' => 0,
                'width' => 32,
                'height' => 14,
                'status' => 'on',
                'installed_date' => null,
                'created_at' => '2026-07-23 00:58:29',
                'updated_at' => '2026-07-23 01:17:47',
            ],
            [
                'floor_id' => 5,
                'lamp_type_id' => 8,
                'code' => 'L-0376',
                'position_x' => 46,
                'position_y' => 58,
                'rotation' => 0,
                'width' => 32,
                'height' => 14,
                'status' => 'on',
                'installed_date' => null,
                'created_at' => '2026-07-23 00:58:35',
                'updated_at' => '2026-07-23 01:16:42',
            ],
            [
                'floor_id' => 5,
                'lamp_type_id' => 8,
                'code' => 'L-0377',
                'position_x' => 46,
                'position_y' => 59,
                'rotation' => 0,
                'width' => 32,
                'height' => 14,
                'status' => 'on',
                'installed_date' => null,
                'created_at' => '2026-07-23 00:58:40',
                'updated_at' => '2026-07-23 01:16:48',
            ],
            [
                'floor_id' => 5,
                'lamp_type_id' => 8,
                'code' => 'L-0378',
                'position_x' => 56,
                'position_y' => 20,
                'rotation' => 0,
                'width' => 32,
                'height' => 14,
                'status' => 'on',
                'installed_date' => null,
                'created_at' => '2026-07-23 00:58:45',
                'updated_at' => '2026-07-23 01:00:55',
            ],
            [
                'floor_id' => 5,
                'lamp_type_id' => 8,
                'code' => 'L-0379',
                'position_x' => 56,
                'position_y' => 22,
                'rotation' => 0,
                'width' => 32,
                'height' => 14,
                'status' => 'on',
                'installed_date' => null,
                'created_at' => '2026-07-23 01:00:14',
                'updated_at' => '2026-07-23 01:01:59',
            ],
            [
                'floor_id' => 5,
                'lamp_type_id' => 8,
                'code' => 'L-0380',
                'position_x' => 56,
                'position_y' => 32,
                'rotation' => 0,
                'width' => 32,
                'height' => 14,
                'status' => 'on',
                'installed_date' => null,
                'created_at' => '2026-07-23 01:00:19',
                'updated_at' => '2026-07-23 01:03:15',
            ],
            [
                'floor_id' => 5,
                'lamp_type_id' => 8,
                'code' => 'L-0381',
                'position_x' => 56,
                'position_y' => 34,
                'rotation' => 0,
                'width' => 32,
                'height' => 14,
                'status' => 'on',
                'installed_date' => null,
                'created_at' => '2026-07-23 01:00:24',
                'updated_at' => '2026-07-23 01:03:18',
            ],
            [
                'floor_id' => 5,
                'lamp_type_id' => 8,
                'code' => 'L-0382',
                'position_x' => 56,
                'position_y' => 45,
                'rotation' => 0,
                'width' => 32,
                'height' => 14,
                'status' => 'on',
                'installed_date' => null,
                'created_at' => '2026-07-23 01:00:29',
                'updated_at' => '2026-07-26 18:35:06',
            ],
            [
                'floor_id' => 5,
                'lamp_type_id' => 8,
                'code' => 'L-0383',
                'position_x' => 56,
                'position_y' => 47,
                'rotation' => 0,
                'width' => 32,
                'height' => 14,
                'status' => 'on',
                'installed_date' => null,
                'created_at' => '2026-07-23 01:00:34',
                'updated_at' => '2026-07-23 01:19:07',
            ],
            [
                'floor_id' => 5,
                'lamp_type_id' => 8,
                'code' => 'L-0384',
                'position_x' => 56,
                'position_y' => 57,
                'rotation' => 0,
                'width' => 32,
                'height' => 14,
                'status' => 'on',
                'installed_date' => null,
                'created_at' => '2026-07-23 01:00:38',
                'updated_at' => '2026-07-23 01:03:43',
            ],
            [
                'floor_id' => 5,
                'lamp_type_id' => 8,
                'code' => 'L-0385',
                'position_x' => 56,
                'position_y' => 59,
                'rotation' => 0,
                'width' => 32,
                'height' => 14,
                'status' => 'on',
                'installed_date' => null,
                'created_at' => '2026-07-23 01:00:43',
                'updated_at' => '2026-07-23 01:04:07',
            ],
            [
                'floor_id' => 5,
                'lamp_type_id' => 8,
                'code' => 'L-0386',
                'position_x' => 66,
                'position_y' => 20,
                'rotation' => 0,
                'width' => 32,
                'height' => 14,
                'status' => 'on',
                'installed_date' => null,
                'created_at' => '2026-07-23 01:03:55',
                'updated_at' => '2026-07-23 01:04:02',
            ],
            [
                'floor_id' => 5,
                'lamp_type_id' => 8,
                'code' => 'L-0387',
                'position_x' => 66,
                'position_y' => 22,
                'rotation' => 0,
                'width' => 32,
                'height' => 14,
                'status' => 'on',
                'installed_date' => null,
                'created_at' => '2026-07-23 01:04:20',
                'updated_at' => '2026-07-23 01:04:25',
            ],
            [
                'floor_id' => 5,
                'lamp_type_id' => 8,
                'code' => 'L-0388',
                'position_x' => 66,
                'position_y' => 32,
                'rotation' => 0,
                'width' => 32,
                'height' => 14,
                'status' => 'on',
                'installed_date' => null,
                'created_at' => '2026-07-23 01:04:32',
                'updated_at' => '2026-07-23 01:04:45',
            ],
            [
                'floor_id' => 5,
                'lamp_type_id' => 8,
                'code' => 'L-0389',
                'position_x' => 66,
                'position_y' => 34,
                'rotation' => 0,
                'width' => 32,
                'height' => 14,
                'status' => 'on',
                'installed_date' => null,
                'created_at' => '2026-07-23 01:04:50',
                'updated_at' => '2026-07-23 01:05:03',
            ],
            [
                'floor_id' => 5,
                'lamp_type_id' => 8,
                'code' => 'L-0390',
                'position_x' => 66,
                'position_y' => 45,
                'rotation' => 0,
                'width' => 32,
                'height' => 14,
                'status' => 'on',
                'installed_date' => null,
                'created_at' => '2026-07-23 01:05:49',
                'updated_at' => '2026-07-23 01:19:12',
            ],
            [
                'floor_id' => 5,
                'lamp_type_id' => 8,
                'code' => 'L-0391',
                'position_x' => 66,
                'position_y' => 47,
                'rotation' => 0,
                'width' => 32,
                'height' => 14,
                'status' => 'on',
                'installed_date' => null,
                'created_at' => '2026-07-23 01:06:15',
                'updated_at' => '2026-07-23 01:19:18',
            ],
            [
                'floor_id' => 5,
                'lamp_type_id' => 8,
                'code' => 'L-0392',
                'position_x' => 66,
                'position_y' => 57,
                'rotation' => 0,
                'width' => 32,
                'height' => 14,
                'status' => 'on',
                'installed_date' => null,
                'created_at' => '2026-07-23 01:06:31',
                'updated_at' => '2026-07-23 01:07:08',
            ],
            [
                'floor_id' => 5,
                'lamp_type_id' => 8,
                'code' => 'L-0393',
                'position_x' => 66,
                'position_y' => 59,
                'rotation' => 0,
                'width' => 32,
                'height' => 14,
                'status' => 'on',
                'installed_date' => null,
                'created_at' => '2026-07-23 01:06:42',
                'updated_at' => '2026-07-23 01:07:12',
            ],
            [
                'floor_id' => 5,
                'lamp_type_id' => 8,
                'code' => 'L-0394',
                'position_x' => 89,
                'position_y' => 82,
                'rotation' => 0,
                'width' => 32,
                'height' => 14,
                'status' => 'on',
                'installed_date' => null,
                'created_at' => '2026-07-23 01:08:43',
                'updated_at' => '2026-07-23 01:08:54',
            ],
            [
                'floor_id' => 5,
                'lamp_type_id' => 8,
                'code' => 'L-0395',
                'position_x' => 89,
                'position_y' => 84,
                'rotation' => 0,
                'width' => 32,
                'height' => 14,
                'status' => 'on',
                'installed_date' => null,
                'created_at' => '2026-07-23 01:09:02',
                'updated_at' => '2026-07-23 01:19:56',
            ],
            [
                'floor_id' => 5,
                'lamp_type_id' => 8,
                'code' => 'L-0396',
                'position_x' => 78,
                'position_y' => 83,
                'rotation' => 0,
                'width' => 32,
                'height' => 14,
                'status' => 'on',
                'installed_date' => null,
                'created_at' => '2026-07-23 01:09:17',
                'updated_at' => '2026-07-23 01:19:44',
            ],
            [
                'floor_id' => 5,
                'lamp_type_id' => 8,
                'code' => 'L-0397',
                'position_x' => 78,
                'position_y' => 85,
                'rotation' => 0,
                'width' => 32,
                'height' => 14,
                'status' => 'on',
                'installed_date' => null,
                'created_at' => '2026-07-23 01:09:32',
                'updated_at' => '2026-07-23 01:19:51',
            ],
            [
                'floor_id' => 5,
                'lamp_type_id' => 8,
                'code' => 'L-0398',
                'position_x' => 66,
                'position_y' => 76,
                'rotation' => 0,
                'width' => 32,
                'height' => 14,
                'status' => 'on',
                'installed_date' => null,
                'created_at' => '2026-07-23 01:09:52',
                'updated_at' => '2026-07-23 01:10:00',
            ],
            [
                'floor_id' => 5,
                'lamp_type_id' => 8,
                'code' => 'L-0399',
                'position_x' => 66,
                'position_y' => 78,
                'rotation' => 0,
                'width' => 32,
                'height' => 14,
                'status' => 'on',
                'installed_date' => null,
                'created_at' => '2026-07-23 01:10:06',
                'updated_at' => '2026-07-23 01:20:38',
            ],
            [
                'floor_id' => 5,
                'lamp_type_id' => 8,
                'code' => 'L-0400',
                'position_x' => 66,
                'position_y' => 87,
                'rotation' => 0,
                'width' => 32,
                'height' => 14,
                'status' => 'on',
                'installed_date' => null,
                'created_at' => '2026-07-23 01:10:17',
                'updated_at' => '2026-07-23 01:10:31',
            ],
            [
                'floor_id' => 5,
                'lamp_type_id' => 8,
                'code' => 'L-0401',
                'position_x' => 66,
                'position_y' => 89,
                'rotation' => 0,
                'width' => 32,
                'height' => 14,
                'status' => 'on',
                'installed_date' => null,
                'created_at' => '2026-07-23 01:10:35',
                'updated_at' => '2026-07-23 01:10:49',
            ],
            [
                'floor_id' => 5,
                'lamp_type_id' => 6,
                'code' => 'L-0402',
                'position_x' => 49,
                'position_y' => 77,
                'rotation' => 0,
                'width' => 32,
                'height' => 14,
                'status' => 'on',
                'installed_date' => null,
                'created_at' => '2026-07-23 01:11:57',
                'updated_at' => '2026-07-23 01:12:46',
            ],
            [
                'floor_id' => 5,
                'lamp_type_id' => 6,
                'code' => 'L-0403',
                'position_x' => 55,
                'position_y' => 77,
                'rotation' => 0,
                'width' => 32,
                'height' => 14,
                'status' => 'on',
                'installed_date' => null,
                'created_at' => '2026-07-23 01:12:13',
                'updated_at' => '2026-07-23 01:20:43',
            ],
            [
                'floor_id' => 5,
                'lamp_type_id' => 6,
                'code' => 'L-0404',
                'position_x' => 49,
                'position_y' => 88,
                'rotation' => 0,
                'width' => 32,
                'height' => 14,
                'status' => 'on',
                'installed_date' => null,
                'created_at' => '2026-07-23 01:12:44',
                'updated_at' => '2026-07-23 01:12:54',
            ],
            [
                'floor_id' => 5,
                'lamp_type_id' => 6,
                'code' => 'L-0406',
                'position_x' => 55,
                'position_y' => 88,
                'rotation' => 0,
                'width' => 32,
                'height' => 14,
                'status' => 'on',
                'installed_date' => null,
                'created_at' => '2026-07-23 01:13:01',
                'updated_at' => '2026-07-23 01:13:25',
            ],
            [
                'floor_id' => 5,
                'lamp_type_id' => 6,
                'code' => 'L-0407',
                'position_x' => 42,
                'position_y' => 77,
                'rotation' => 0,
                'width' => 32,
                'height' => 14,
                'status' => 'on',
                'installed_date' => null,
                'created_at' => '2026-07-23 01:14:12',
                'updated_at' => '2026-07-23 01:14:20',
            ],
            [
                'floor_id' => 5,
                'lamp_type_id' => 6,
                'code' => 'L-0408',
                'position_x' => 42,
                'position_y' => 89,
                'rotation' => 0,
                'width' => 32,
                'height' => 14,
                'status' => 'on',
                'installed_date' => null,
                'created_at' => '2026-07-23 01:14:31',
                'updated_at' => '2026-07-23 01:14:31',
            ],
            [
                'floor_id' => 5,
                'lamp_type_id' => 6,
                'code' => 'L-0409',
                'position_x' => 21,
                'position_y' => 77,
                'rotation' => 0,
                'width' => 32,
                'height' => 14,
                'status' => 'on',
                'installed_date' => null,
                'created_at' => '2026-07-23 01:26:48',
                'updated_at' => '2026-07-23 01:27:18',
            ],
            [
                'floor_id' => 5,
                'lamp_type_id' => 6,
                'code' => 'L-0414',
                'position_x' => 26,
                'position_y' => 77,
                'rotation' => 0,
                'width' => 32,
                'height' => 14,
                'status' => 'on',
                'installed_date' => null,
                'created_at' => '2026-07-23 01:26:57',
                'updated_at' => '2026-07-23 01:30:57',
            ],
            [
                'floor_id' => 5,
                'lamp_type_id' => 6,
                'code' => 'L-0415',
                'position_x' => 21,
                'position_y' => 90,
                'rotation' => 0,
                'width' => 32,
                'height' => 14,
                'status' => 'on',
                'installed_date' => null,
                'created_at' => '2026-07-23 01:27:30',
                'updated_at' => '2026-07-23 01:27:50',
            ],
            [
                'floor_id' => 5,
                'lamp_type_id' => 6,
                'code' => 'L-0416',
                'position_x' => 26,
                'position_y' => 90,
                'rotation' => 0,
                'width' => 32,
                'height' => 14,
                'status' => 'on',
                'installed_date' => null,
                'created_at' => '2026-07-23 01:27:39',
                'updated_at' => '2026-07-23 01:27:44',
            ],
            [
                'floor_id' => 5,
                'lamp_type_id' => 10,
                'code' => 'L-0417',
                'position_x' => 33,
                'position_y' => 76,
                'rotation' => 0,
                'width' => 32,
                'height' => 4,
                'status' => 'on',
                'installed_date' => null,
                'created_at' => '2026-07-24 00:33:40',
                'updated_at' => '2026-07-24 00:33:40',
            ],
            [
                'floor_id' => 5,
                'lamp_type_id' => 10,
                'code' => 'L-0422',
                'position_x' => 33,
                'position_y' => 78,
                'rotation' => 0,
                'width' => 32,
                'height' => 4,
                'status' => 'on',
                'installed_date' => null,
                'created_at' => '2026-07-24 00:33:50',
                'updated_at' => '2026-07-24 00:34:07',
            ],
            [
                'floor_id' => 5,
                'lamp_type_id' => 10,
                'code' => 'L-0423',
                'position_x' => 33,
                'position_y' => 79,
                'rotation' => 0,
                'width' => 32,
                'height' => 4,
                'status' => 'on',
                'installed_date' => null,
                'created_at' => '2026-07-24 00:33:57',
                'updated_at' => '2026-07-24 00:34:13',
            ],
            [
                'floor_id' => 5,
                'lamp_type_id' => 10,
                'code' => 'L-0424',
                'position_x' => 33,
                'position_y' => 88,
                'rotation' => 0,
                'width' => 32,
                'height' => 4,
                'status' => 'on',
                'installed_date' => null,
                'created_at' => '2026-07-24 00:34:22',
                'updated_at' => '2026-07-24 00:34:22',
            ],
            [
                'floor_id' => 5,
                'lamp_type_id' => 10,
                'code' => 'L-0425',
                'position_x' => 33,
                'position_y' => 89,
                'rotation' => 0,
                'width' => 32,
                'height' => 4,
                'status' => 'on',
                'installed_date' => null,
                'created_at' => '2026-07-24 00:34:31',
                'updated_at' => '2026-07-24 00:34:38',
            ],
            [
                'floor_id' => 5,
                'lamp_type_id' => 10,
                'code' => 'L-0426',
                'position_x' => 33,
                'position_y' => 91,
                'rotation' => 0,
                'width' => 32,
                'height' => 4,
                'status' => 'on',
                'installed_date' => null,
                'created_at' => '2026-07-24 00:34:46',
                'updated_at' => '2026-07-24 00:34:53',
            ],
        ];

        $mappedLamps = [];
        foreach ($rawLamps as $lamp) {
            $lamp['floor_id'] = $floors['L1']->id;
            $lamp['lamp_type_id'] = $typeMapping[$lamp['lamp_type_id']] ?? $lampTypes['tl_2']->id;
            $mappedLamps[] = $lamp;
        }

        Lamp::insert($mappedLamps);

        // 5. Seed Inventory
        $inventories = [];
        $inventories['halogen'] = Inventory::create(['lamp_type_id' => $lampTypes['halogen']->id, 'stock_quantity' => 150, 'min_stock' => 15]);
        $inventories['downlight'] = Inventory::create(['lamp_type_id' => $lampTypes['downlight']->id, 'stock_quantity' => 200, 'min_stock' => 20]);
        $inventories['t5'] = Inventory::create(['lamp_type_id' => $lampTypes['t5']->id, 'stock_quantity' => 85, 'min_stock' => 10]);
        $inventories['tl_1'] = Inventory::create(['lamp_type_id' => $lampTypes['tl_1']->id, 'stock_quantity' => 100, 'min_stock' => 10]);
        $inventories['tl_2'] = Inventory::create(['lamp_type_id' => $lampTypes['tl_2']->id, 'stock_quantity' => 90, 'min_stock' => 10]);

        // 6. Seed Inventory Transactions
        foreach ($inventories as $inv) {
            for ($i = 0; $i < 3; $i++) {
                InventoryTransaction::create([
                    'inventory_id' => $inv->id,
                    'type' => 'masuk',
                    'quantity' => rand(20, 100),
                    'transaction_date' => Carbon::now()->subDays(rand(5, 120)),
                    'reference' => 'PO-' . rand(1000, 9999),
                    'notes' => 'Restock awal dari supplier',
                ]);
            }
        }

        // 7. Seed Transactions History
        $floorsArray = Floor::all();
        foreach ($floorsArray as $fl) {
            for ($i = 0; $i < 5; $i++) {
                $randomType = array_rand($lampTypes);
                Transaction::create([
                    'floor_id' => $fl->id,
                    'lamp_type_id' => $lampTypes[$randomType]->id,
                    'type' => 'pemasangan',
                    'quantity' => rand(1, 4),
                    'transaction_date' => Carbon::now()->subDays(rand(1, 60)),
                    'technician' => 'Ahmad',
                    'notes' => 'Pemasangan unit baru saat setup lantai',
                ]);
            }
        }
    }

    /**
     * Helper to calculate a clean grid layout of lamps inside floor coordinates
     */
    private function seedLampsInGrid(Floor $floor, LampType $type, int $count, float $startX, float $startY, float $endX, float $endY, int $rotation = 0, int $customCols = null): void
    {
        $positions = [];
        $cols = $customCols ?: ceil(sqrt($count));
        $rows = ceil($count / $cols);

        $stepX = $cols > 1 ? ($endX - $startX) / ($cols - 1) : 0;
        $stepY = $rows > 1 ? ($endY - $startY) / ($rows - 1) : 0;

        for ($r = 0; $r < $rows; $r++) {
            for ($c = 0; $c < $cols; $c++) {
                if (count($positions) >= $count)
                    break 2;
                $x = $startX + ($c * $stepX);
                $y = $startY + ($r * $stepY);
                $positions[] = ['x' => round($x, 2), 'y' => round($y, 2)];
            }
        }

        foreach ($positions as $pos) {
            $w = 20;
            $h = 20;
            if ($type->type === 'T5') {
                $w = 32;
                $h = 4;
            } elseif ($type->type === 'TL 1') {
                $w = 32;
                $h = 6;
            } elseif ($type->type === 'TL 2') {
                $w = 32;
                $h = 14;
            }

            Lamp::create([
                'floor_id' => $floor->id,
                'lamp_type_id' => $type->id,
                'code' => 'L-' . str_pad($this->lampCounter++, 4, '0', STR_PAD_LEFT),
                'position_x' => $pos['x'],
                'position_y' => $pos['y'],
                'rotation' => $rotation,
                'width' => $w,
                'height' => $h,
                'status' => 'on',  // status langsung aktif (warna hijau)
                'installed_date' => Carbon::now()->subDays(rand(10, 180)),
            ]);
        }
    }
}
